name: romeo
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  speech_to_text: ^7.3.0
  http: ^1.6.0
  flutter_tts: ^4.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/app_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/logo/app_logo.png

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
